feat: bulk add a number of otel instrumentations
elastic/elastic-otel-node pull request #231
Opened 2024-06-13 23:37 UTC by trentm

```
@opentelemetry/instrumentation-connect
@opentelemetry/instrumentation-cucumber
@opentelemetry/instrumentation-dataloader
@opentelemetry/instrumentation-dns
@opentelemetry/instrumentation-generic-pool
@opentelemetry/instrumentation-knex
@opentelemetry/instrumentation-koa
@opentelemetry/instrumentation-lru-memoizer
@opentelemetry/instrumentation-memcached
@opentelemetry/instrumentation-nestjs-core
@opentelemetry/instrumentation-net
@opentelemetry/instrumentation-restify
@opentelemetry/instrumentation-router
@opentelemetry/instrumentation-socket.io
```

---

Notably no tests have been added for these. The minor justification being that these are instrumentations that seem to very rarely change upstream. We can come back and add tests for these as/if needed.

2024-06-14 00:07 UTC, trentm commented
Draft for now. I need to work through tests and ignore instr-dns and instr-net spans that are throwing off assertions.
It would be nice to have `OTEL_NODE_DISABLED_INSTRUMENTATIONS` that auto-instrumentations-node is getting. Then the test fixtures coudl run with `OTEL_NODE_DISABLED_INSTRUMENTATIONS: 'dns,net'`.

2024-06-18 11:12 UTC, david-luna commented
> It would be nice to have OTEL_NODE_DISABLED_INSTRUMENTATIONS that auto-instrumentations-node is getting. Then the test fixtures coudl run with OTEL_NODE_DISABLED_INSTRUMENTATIONS: 'dns,net'.

Do you plan to do it in this PR or you prefer to have a dedicated issue to honor the env var `OTEL_NODE_DISABLED_INSTRUMENTATIONS` ?

2024-06-18 11:12 UTC, david-luna requested changes

2024-06-18 11:12 UTC, david-luna commented on packages/opentelemetry-node/lib/instrumentations.js
> + *  "@opentelemetry/instrumentation-memcached": import('@opentelemetry/instrumentation').InstrumentationConfig | InstrumentationFactory,
this instrumentation is exporting a config interface with the same name but actually it has an extra property.

ref: https://github.com/open-telemetry/opentelemetry-js-contrib/blob/2dc2f72e5a86aa9e1220a26f78878070acde8424/plugins/node/opentelemetry-instrumentation-memcached/src/types.ts#L19

```suggestion
 *  "@opentelemetry/instrumentation-memcached": import('@opentelemetry/instrumentation-memcached').InstrumentationConfig | InstrumentationFactory,
```

2024-06-18 18:35 UTC, trentm commented
> Do you plan to do it in this PR or you prefer to have a dedicated issue to honor the env var `OTEL_NODE_DISABLED_INSTRUMENTATIONS` ?

Not for this PR, no. I think when auto-instrumentations-node has this merged we should consider supporting the same envvar.  And then when we do we could switch the tests cases to use that instead of the `filterOut...()` hack I added here.

2024-06-20 17:47 UTC, david-luna approved these changes

2024-06-20 20:45 UTC, merged