feat(otel-node): handle enable/disable instrumentations via env vars
elastic/elastic-otel-node pull request #318
Opened 2024-08-08 09:30 UTC by david-luna

2024-08-08 09:31 UTC, david-luna commented on packages/opentelemetry-node/lib/instrumentations.js
> +        // XXX: discuss what takes precedence if `opts` argument id passed in
note for reviewer: leave your thoughts here :)

2024-08-08 16:10 UTC, trentm commented on packages/opentelemetry-node/test/OTEL_NODE_ENABLE_DISABLE_INSTRUMENTATIONS.test.js
> +test('OTEL_NODE_RESOUCE_DETECTORS', (suite) => {
```suggestion
test('OTEL_NODE_ENABLED_INSTRUMENTATIONS, OTEL_NODE_DISABLED_INSTRUMENTATIONS', (suite) => {
```

2024-08-09 14:31 UTC, david-luna commented on packages/opentelemetry-node/lib/instrumentations.js
> +        // XXX: discuss what takes precedence if `opts` argument id passed in
if I got it right form our last meeting I've done the changes 
- env vars take precedence over config
- if env var enables a instrumentation disabled by config it becomes enabled

2024-08-09 14:32 UTC, david-luna commented on packages/opentelemetry-node/lib/instrumentations.js
> +function parseStringList(str) {
I ended updating it to something more complex

2024-08-09 17:56 UTC, trentm requested changes
One change to match the auto-instr-node behaviour (DISABLED envvar wins). Otherwise looks good.

2024-08-09 17:56 UTC, trentm commented on packages/opentelemetry-node/lib/instrumentations.js
> +            if (!enabledFromEnv) {
I think this is wrong. If an instrumentation name is listed in both OTEL_NODE_ENABLED_INSTRUMENTATIONS and OTEL_NODE_DISABLED_INSTRUMENTATIONS, then it should be *disabled*. I.e. disabling wins. That is what auto-instr-node is doing:

https://github.com/open-telemetry/opentelemetry-js-contrib/blob/60a99c98fd3a5594c7c2234184f06166b375e707/metapackages/auto-instrumentations-node/test/utils.test.ts#L117-L134

2024-08-12 19:05 UTC, trentm approved these changes

2024-08-13 15:29 UTC, merged